title: "Manuel Joriatti"
description: "Textes proposés à La Riposte."

theme: minima
permalink: :year-:month-:day-:title:output_ext

plugins:
    - jekyll-sitemap

exclude: ["template.md", "README.md"]
