title: "Manuel Joriatti"
url: "https://mjoriatti.github.io"
description: "Textes proposés à La Riposte."

theme: jekyll-theme-minimal
permalink: :year-:month-:day-:title:output_ext

plugins:
    - jekyll-sitemap

exclude: ["template.md", "README.md"]
