title: "Manuel Joriatti"
description: "Textes proposés à La Riposte"

url: "http://mjoriatti.github.io/lariposte"
repository: "mjoriatti/lariposte"

theme: jekyll-theme-minimal
plugins:
    - jekyll-sitemap

exclude: ["template.md", "Gemfile"]
